import type { BizNaviInquiryItem } from './dto';

// ⚠️ 데모용 임시(Mock) 데이터입니다. 이름/주민등록번호는 모두 가상의 예시 값입니다.
export const BIZ_NAVI_INQUIRY_MOCK_LIST: BizNaviInquiryItem[] = [
  {
    id: '1',
    title: '[예시] 기타 문의 심사 요청드립니다',
    status: '답변완료',
    inquiryDate: '26.03.18',
    target: '샘플고객1',
    answerer: '샘플담당자1',
    content: '(예시) 기타 문의에 대한 심사 요청을 드립니다. 확인 부탁드립니다.',
    customerName: '샘플고객1',
    residentNumberFront: '000000',
    residentNumberBack: '0******',
    reviewer: '샘플심사자1',
    answerContent: '(예시) 확인 완료되었습니다.'
  },
  {
    id: '2',
    title: '[예시] 심사 요청',
    status: '답변완료',
    inquiryDate: '26.03.18',
    target: '샘플고객1',
    answerer: '샘플담당자1',
    content: '(예시) 청약 심사 요청 드립니다.',
    customerName: '샘플고객1',
    residentNumberFront: '000000',
    residentNumberBack: '0******',
    reviewer: '샘플심사자1',
    answerContent: '(예시) 심사 처리 완료했습니다.'
  },
  {
    id: '3',
    title: '[예시] 기타 문의 심사 요청드립니다',
    status: '답변미완료',
    inquiryDate: '26.03.18',
    target: '샘플고객1',
    answerer: '샘플담당자1',
    content: '(예시) 기타 문의에 대한 심사 요청을 드립니다. 확인 부탁드립니다.',
    customerName: '샘플고객1',
    residentNumberFront: '000000',
    residentNumberBack: '0******',
    reviewer: '',
    answerContent: ''
  },
  {
    id: '4',
    title: '[예시] 인수 요청 거절 사유 확인 부탁드립니다',
    status: '답변미완료',
    inquiryDate: '26.03.18',
    target: '샘플고객1',
    answerer: '샘플담당자1',
    content: '(예시) 인수 요청이 거절된 사유를 확인하고 싶습니다.',
    customerName: '샘플고객1',
    residentNumberFront: '000000',
    residentNumberBack: '0******',
    reviewer: '',
    answerContent: ''
  },
  {
    id: '5',
    title: '[예시] 심사 요청',
    status: '답변완료',
    inquiryDate: '26.03.18',
    target: '샘플고객1',
    answerer: '샘플담당자1',
    content: '(예시) 청약 심사 요청 드립니다.',
    customerName: '샘플고객1',
    residentNumberFront: '000000',
    residentNumberBack: '0******',
    reviewer: '샘플심사자1',
    answerContent: '(예시) 처리 완료.'
  },
  {
    id: '6',
    title: '[예시] 인수 요청 거절 사유 확인 부탁드립니다',
    status: '답변미완료',
    inquiryDate: '26.03.18',
    target: '샘플고객1',
    answerer: '샘플담당자1',
    content: '(예시) 인수 요청이 거절된 사유를 확인하고 싶습니다.',
    customerName: '샘플고객1',
    residentNumberFront: '000000',
    residentNumberBack: '0******',
    reviewer: '',
    answerContent: ''
  },
  {
    id: '7',
    title: '[예시] 심사 요청',
    status: '답변완료',
    inquiryDate: '26.03.18',
    target: '샘플고객1',
    answerer: '샘플담당자1',
    content: '(예시) 청약 심사 요청 드립니다.',
    customerName: '샘플고객1',
    residentNumberFront: '000000',
    residentNumberBack: '0******',
    reviewer: '샘플심사자1',
    answerContent: '(예시) 심사 완료.'
  },
  {
    id: '8',
    title: '[예시] 보험료 납입 변경 문의',
    status: '답변완료',
    inquiryDate: '26.03.17',
    target: '샘플고객2',
    answerer: '샘플담당자2',
    content: '(예시) 보험료 납입 방법 변경을 요청합니다.',
    customerName: '샘플고객2',
    residentNumberFront: '000000',
    residentNumberBack: '0******',
    reviewer: '샘플담당자2',
    answerContent: '(예시) 변경 처리 완료했습니다.'
  },
  {
    id: '9',
    title: '[예시] 계약 서류 재발급 요청',
    status: '답변미완료',
    inquiryDate: '26.03.17',
    target: '샘플고객3',
    answerer: '샘플담당자3',
    content: '(예시) 계약서를 분실하여 재발급을 요청합니다.',
    customerName: '샘플고객3',
    residentNumberFront: '000000',
    residentNumberBack: '0******',
    reviewer: '',
    answerContent: ''
  },
  {
    id: '10',
    title: '[예시] 앱 로그인 오류 문의',
    status: '답변완료',
    inquiryDate: '26.03.16',
    target: '샘플고객4',
    answerer: '샘플담당자4',
    content: '(예시) 앱 로그인 시 오류가 지속 발생합니다.',
    customerName: '샘플고객4',
    residentNumberFront: '000000',
    residentNumberBack: '0******',
    reviewer: '샘플담당자4',
    answerContent: '(예시) 오류 수정 완료.'
  },
  {
    id: '11',
    title: '[예시] 특약 해지 가능 여부 문의',
    status: '답변미완료',
    inquiryDate: '26.03.16',
    target: '샘플고객5',
    answerer: '샘플담당자5',
    content: '(예시) 일부 특약 해지 가능 여부를 문의합니다.',
    customerName: '샘플고객5',
    residentNumberFront: '000000',
    residentNumberBack: '0******',
    reviewer: '',
    answerContent: ''
  },
  {
    id: '12',
    title: '[예시] 청약 4단계 화면 오류 보고',
    status: '답변완료',
    inquiryDate: '26.03.15',
    target: '샘플고객6',
    answerer: '샘플담당자6',
    content: '(예시) 청약 4단계에서 화면이 멈추는 현상이 발생합니다.',
    customerName: '샘플고객6',
    residentNumberFront: '000000',
    residentNumberBack: '0******',
    reviewer: '샘플담당자6',
    answerContent: '(예시) 수정 배포 완료.'
  },
  {
    id: '13',
    title: '[예시] 보험증권 이메일 재발송 요청',
    status: '답변완료',
    inquiryDate: '26.03.15',
    target: '샘플고객7',
    answerer: '샘플담당자7',
    content: '(예시) 보험증권 이메일 재발송을 요청합니다.',
    customerName: '샘플고객7',
    residentNumberFront: '000000',
    residentNumberBack: '0******',
    reviewer: '샘플담당자7',
    answerContent: '(예시) 재발송 완료.'
  },
  {
    id: '14',
    title: '[예시] 수익자 변경 절차 문의',
    status: '답변미완료',
    inquiryDate: '26.03.14',
    target: '샘플고객8',
    answerer: '샘플담당자8',
    content: '(예시) 수익자 변경 절차를 문의합니다.',
    customerName: '샘플고객8',
    residentNumberFront: '000000',
    residentNumberBack: '0******',
    reviewer: '',
    answerContent: ''
  },
  {
    id: '15',
    title: '[예시] 환급금 조회 오류 문의',
    status: '답변완료',
    inquiryDate: '26.03.14',
    target: '샘플고객9',
    answerer: '샘플담당자9',
    content: '(예시) 환급금 조회 화면에서 오류가 발생합니다.',
    customerName: '샘플고객9',
    residentNumberFront: '000000',
    residentNumberBack: '0******',
    reviewer: '샘플담당자9',
    answerContent: '(예시) 오류 해결 완료.'
  }
];
